---
name: Build Image when PR is opened
on:
  pull_request:
    types:
      - opened
    branches:
      - master
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: linux-app-astrafy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: Build Docker Image
        run: docker build -t $GITHUB_SHA:latest .

      - name: Echo
        run: echo $GITHUB_SHA