---
name: Build and Push App Image to Google Cloud Artifact Registry 
on:
  push:
    branches:
      - master
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: linux_tweet_app
      PROJECT_ID: linux-app-astrafy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet

      - name: Tag Docker Image to Artifact Registry
        run: |-
          docker tag $IMAGE_NAME:latest europe-west2-docker.pkg.dev/linux-app-astrafy/linux-app/$IMAGE_NAME:latest
      
      - name: Push Docker Image to Artifact Registry
        run: |-
          docker push europe-west2-docker.pkg.dev/linux-app-astrafy/linux-app/$IMAGE_NAME:latest
