---
name: Build Image and deploy on Tag
on:
  release:
    branches:
      - master  
jobs:
  build-push-gcr:
    name: Build and Push to GCP when main is taged
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: linux-app-astrafy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
          
      - name: Build Docker Image
        run: docker build -t $GITHUB_REF:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet

      - name: Tag Docker Image to Artifact Registry
        run: |-
          docker tag $GITHUB_REF:latest europe-west2-docker.pkg.dev/linux-app-astrafy/linux-app/$GITHUB_REF:latest
      
      - name: Push Docker Image to Artifact Registry
        run: |-
          docker push europe-west2-docker.pkg.dev/linux-app-astrafy/linux-app/$GITHUB_REF:latest
